Map<String, dynamic> teamsRank = {
  "": "Let food be thy medicine and medicine be thy food \n                       Explore our fun recipes",
  "Macaroni and Cheese":
      " Step 1 \n \n Bring a large pot of lightly salted water to a boil. Cook elbow macaroni in the boiling water, stirring occasionally until cooked through but firm to the bite, 8 minutes \n \n Step 2 \n \n At the same time, melt butter in a saucepan over medium heat. Add flour, salt, and pepper and stir until smooth, about 5 minutes. Pour in milk slowly, while stirring continuously. Continue to cook and stir until mixture is smooth and bubbling, about 5 minutes, making sure the milk doesn't burn \n \n Step 3 \n \n Add Cheddar cheese and stir until melted, 2 to 4 minutes. \n step 4 \n \n Drain macaroni and fold into cheese sauce until coated.",
  "Ramen":
      "STEP 1 \n \nCook the noodles with the sachet of flavouring provided (or use stock instead of the sachet, if you have it). Add the spring onions and pak choi for the final min.\n \n STEP 2 \n \n Meanwhile, simmer the egg for 6 mins from boiling, run it under cold water to stop it cooking, then peel it. Toast the sesame seeds in a frying pan.\n \n STEP 3\n \n Tip the noodles and greens into a deep bowl, halve the boiled egg and place on top. Sprinkle with sesame seeds, then drizzle with the sauce or sesame oil provided with the noodles, and chilli sauce, if using.",
  "Poha":
      "STEP 1 \n \n Put poha in a colander and wash, not letting it soak too long in the water. Leave in the colander to drain out completely.\n \n STEP 2\n \n Heat the oil and add the asafoetida, mustard seeds, curry leaves and onions along with whole red chillies.\n\n Step 3 \n \n When onions are light brown, add potatoes, and turn around till they look a bit glossy.\n\n STEP 4\n \n Add the turmeric and sauté over low heat till the potatoes are cooked through\n\n.STEP 5\n \n Increase the heat, add salt and poha and mix well. Saute till mixed and heated through.",
  "Latte":
      "STEP 1\n \n To begin making Hot Coffee Latte Recipe, in a large jar with leak-proof lid, add milk and shake vigorously for about 1 minute or two.\n \n STEP 2 \n \nOpen the lid and microwave the jar on a high power for 2 minutes. Make sure the container has space for the milk to foam up.\n\n STEP 3 \n \n In a big mug, add the espresso in equal quantity and hold the mug in a tilted position. Keep adding the frothed milk into one cup from the mug's edge in a steady pattern till the cup is full such that it forms a coffee art on top.\n \n STEP 4\n \n You can optionally sprinkle with a dash of coa powder on top.",
  "Sandwich":
      "STEP 1\n \n Wash and peel 300 grams potatoes (1 large or 2 medium). I prefer to quarter them and steam over a pot just until done. You can also boil the whole potatoes in a pressure cooker for 3 whistles or for 5 to 9 mins in the instant pot depending on the size of your potatoes.\n \n STEP 2\n \n  To a mixing bowl, add \n ½ teaspoon grated ginger, 1 green chili chopped (optional), 1 tbsp chopped coriander leaves , ½ teaspoon red chili powder, 1/4 teaspoon salt (adjust to taste), 1/8 teaspoon turmeric, 1/4 to ½ teaspoon garam masala (adjust to taste) , 1/2 teaspoon coriander powder. \n \n STEP 2 \n \n Pour 1to 2 tsp ghee or oil over the spices. I prefer to use hot ghee as it helps to bring out the aroma of the other ingredients used. However it is optional.\n \n  STEP 3\n \n  Mix up everything. You can also add lemon juice or amchur now.\n \n STEP 4\n \n  Add mashed potato. Mix up everything well. Taste test and add more spices, salt or lemon juice to taste.\n \n STEP 5\n \n  Smear softened butter or ghee on one side of the bread. I prefer ghee. Turn the bread slices to the other side. If you want you can also smear some green chutney or schezwan sauce and then spread the aloo masala. Cover with another slice and smear butter or ghee on the outer side. You can also smear chutney or sauce on both the slices.\n \n STEP 6.\n \n Heat the sandwich griller and grill the sandwiches for 3 to 5 mins until crisp. Alternately you can also toast them on a hot griddle on both the sides until crisp & golden. Cut aloo sandwiches to squares or triangles and serve with green chutney or schezwan sauce.",
};
